version: '3.8'

services:
  app:
    image: node:20-alpine
    networks:
      - network_public
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - CLICKUP_API_KEY=${CLICKUP_API_KEY}
      - CLICKUP_TEAM_ID=${CLICKUP_TEAM_ID}
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.services.clickup.loadbalancer.server.port=3000
        - traefik.http.routers.clickup.rule=Host(`clickup-sync.allfluence.ai`)
        - traefik.http.routers.clickup.entrypoints=websecure
        - traefik.http.routers.clickup.tls=true
        - traefik.http.routers.clickup.tls.certresolver=letsencryptresolver
        - traefik.http.routers.clickup.service=clickup
    working_dir: /app
    command: npx @pedrovaleriolopez/clickup-webhook-server

networks:
  network_public:
    external: true